name: nsaqseek
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.0.2
  get: 4.3.8
  google_fonts: ^2.1.0
  url_launcher: ^6.0.12
  shared_preferences: ^2.0.8
  firebase_messaging: ^11.1.0
  firebase_core: ^1.10.0
  http: ^0.13.4
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
